ALTER TABLE users
ADD COLUMN uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
ADD COLUMN first_name VARCHAR(100) DEFAULT 'N/A' NOT NULL,
ADD COLUMN middle_name VARCHAR(100),
ADD COLUMN last_name VARCHAR(100) DEFAULT 'N/A' NOT NULL,
ADD COLUMN gender VARCHAR(20) CHECK (gender IN ('male','female','nonbinary','unknown')),
ADD COLUMN birth_date DATE,
ADD COLUMN death_date DATE,
ADD COLUMN phone VARCHAR(20),
ADD COLUMN secondary_phone VARCHAR(20),
ADD COLUMN national_id VARCHAR(50) UNIQUE,
ADD COLUMN passport_no VARCHAR(30) UNIQUE,
ADD COLUMN marital_status VARCHAR(20) CHECK (marital_status IN ('single','married','divorced','widowed','other')),
ADD COLUMN nationality_code CHAR(2),
ADD COLUMN place_of_birth VARCHAR(120),
ADD COLUMN timezone VARCHAR(50),
ADD COLUMN language CHAR(5),
ADD COLUMN photo_url TEXT,
ADD COLUMN address_line1 VARCHAR(200),
ADD COLUMN address_line2 VARCHAR(200),
ADD COLUMN city VARCHAR(100),
ADD COLUMN state_region VARCHAR(100),
ADD COLUMN postal_code VARCHAR(20),
ADD COLUMN country_code CHAR(2),
ADD COLUMN notes TEXT,
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
ADD COLUMN deleted_at TIMESTAMPTZ,
ADD COLUMN last_login_at TIMESTAMPTZ,
ADD COLUMN created_by BIGINT,
ADD COLUMN updated_by BIGINT